n1 = int(input("Primeiro numero inteiro: "))
n2 = int(input("Segundo numero inteiro: "))
n3 = float(input("Numero real: "))
print("A=", (n1*2)+(n2/2), "o produto do dobro do primeiro com metade do segundo")
print("B=", (n1*3)+(n3), "a soma do triplo do primeiro com o terceiro.")
print("C=", (n3**3), "o terceiro elevado ao cubo.")